# coding: utf-8

"""
    smallmodelsapi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from electrificationutils.api.ggrfhvac_update_api import GGRFHVACUpdateApi


class TestGGRFHVACUpdateApi(unittest.TestCase):
    """GGRFHVACUpdateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GGRFHVACUpdateApi()

    def tearDown(self) -> None:
        pass

    def test_ggrf_hvac_upgrade_btu_per_watt_hour_ggrf_hvac_upgrade_btu_per_watt_hour_v1_get(self) -> None:
        """Test case for ggrf_hvac_upgrade_btu_per_watt_hour_ggrf_hvac_upgrade_btu_per_watt_hour_v1_get

        Ggrf Hvac Upgrade Btu Per Watt Hour
        """
        pass

    def test_ggrf_hvac_upgrade_electric_to_electric_ggrf_hvac_upgrade_electric_to_electric_v1_get(self) -> None:
        """Test case for ggrf_hvac_upgrade_electric_to_electric_ggrf_hvac_upgrade_electric_to_electric_v1_get

        Ggrf Hvac Upgrade Electric To Electric
        """
        pass

    def test_ggrf_hvac_upgrade_fossil_to_electric_ggrf_hvac_upgrade_fossil_to_electric_v1_get(self) -> None:
        """Test case for ggrf_hvac_upgrade_fossil_to_electric_ggrf_hvac_upgrade_fossil_to_electric_v1_get

        Ggrf Hvac Upgrade Fossil To Electric
        """
        pass


if __name__ == '__main__':
    unittest.main()
