# coding: utf-8

"""
    smallmodelsapi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from electrificationutils.models.upgrade_option import UpgradeOption

class TestUpgradeOption(unittest.TestCase):
    """UpgradeOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpgradeOption(self):
        """Test UpgradeOption"""
        # inst = UpgradeOption()

if __name__ == '__main__':
    unittest.main()
