# coding: utf-8

"""
    smallmodelsapi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from electrificationutils.api.health_data_api import HealthDataApi


class TestHealthDataApi(unittest.TestCase):
    """HealthDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthDataApi()

    def tearDown(self) -> None:
        pass

    def test_query_metrics_health_data_query_v1_get(self) -> None:
        """Test case for query_metrics_health_data_query_v1_get

        Query Metrics
        """
        pass


if __name__ == '__main__':
    unittest.main()
