# coding: utf-8

"""
    smallmodelsapi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from electrificationutils.api.health_impacts_api import HealthImpactsApi


class TestHealthImpactsApi(unittest.TestCase):
    """HealthImpactsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthImpactsApi()

    def tearDown(self) -> None:
        pass

    def test_query_health_impacts(self) -> None:
        """Test case for query_health_impacts

        Query Health Impacts
        """
        pass


if __name__ == '__main__':
    unittest.main()
