# coding: utf-8

# flake8: noqa
"""
    smallmodelsapi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from electrificationutils.models.energy_quantity import EnergyQuantity
from electrificationutils.models.energy_tradeoff import EnergyTradeoff
from electrificationutils.models.group_by import GroupBy
from electrificationutils.models.http_validation_error import HTTPValidationError
from electrificationutils.models.hvac_efficiency_electric_detailed import HvacEfficiencyElectricDetailed
from electrificationutils.models.hvac_efficiency_fossil_fuels import HvacEfficiencyFossilFuels
from electrificationutils.models.hvac_update_results import HvacUpdateResults
from electrificationutils.models.metrics import Metrics
from electrificationutils.models.range_fuel_type import RangeFuelType
from electrificationutils.models.upgrade_option import UpgradeOption
from electrificationutils.models.validation_error import ValidationError
from electrificationutils.models.validation_error_loc_inner import ValidationErrorLocInner
