# coding: utf-8

"""
    smallmodelsapi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GroupBy(str, Enum):
    """
    Enum for valid columns to group the query results by.
    """

    """
    allowed enum values
    """
    IN_SQFT_BIN = 'in_sqft_bin'
    ACS_HOUSING_TYPE = 'acs_housing_type'
    IN_HVAC_COOLING_TYPE = 'in_hvac_cooling_type'
    BASELINE_APPLIANCE_FUEL = 'baseline_appliance_fuel'
    UPGRADE_OPTION = 'upgrade_option'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GroupBy from a JSON string"""
        return cls(json.loads(json_str))


