# coding: utf-8

"""
    smallmodelsapi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RangeFuelType(str, Enum):
    """
    Fuel types inputs that the range upgrade API supports.  Note that we do not support electricity as the input because we are modeling upgrading to electric, and so upgrading from electric would produce no change.
    """

    """
    allowed enum values
    """
    NATURAL_GAS = 'natural_gas'
    PROPANE = 'propane'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RangeFuelType from a JSON string"""
        return cls(json.loads(json_str))


