# coding: utf-8

"""
    smallmodelsapi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class UpgradeOption(str, Enum):
    """
    Enum for valid electrification upgrade options.
    """

    """
    allowed enum values
    """
    HEAT_PUMP_DRYER = 'heat_pump_dryer'
    MEDIUM_EFFICIENCY_HEAT_PUMP_BASIC_INSULATION = 'medium_efficiency_heat_pump_basic_insulation'
    HEAT_PUMP_WATER_HEATER = 'heat_pump_water_heater'
    MEDIUM_EFFICIENCY_HEAT_PUMP = 'medium_efficiency_heat_pump'
    ELECTRIC_RESISTANCE_DRYER = 'electric_resistance_dryer'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UpgradeOption from a JSON string"""
        return cls(json.loads(json_str))


